#!url=https://raw.githubusercontent.com/Cydia8888/loon_config/master/module/bybutter.module
#!name=黄油相机
#!desc=破解会员
#!author=Cydia8888
[Script]
黄油相机=type=http-response,pattern= ^https?:\/\/api4\.bybutter\.com\/v4\/(users\/me$|shop\/me\/privileges$),requires-body=1,script-path= https://raw.githubusercontent.com/Cydia8888/loon_config/master/js/bybutter.js
[MITM]
hostname= %APPEND% api4.bybutter.com
