#!name= UnblockVIP
#!desc= 彩云,度盘,WPS,酷我,Picsew
#!author=Cydia8888
#!homepage=https://github.com/Cydia8888/loon_config
#!主机buy.itunes.apple.com多模块共同，故放在本地
[Script]
百度云加速=type=http-response,pattern=https:\/\/pan\.baidu\.com\/rest\/\d\.\d\/membership\/user,requires-body=1,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Surge/JS/BaiduCloud.js
彩云天气pro=type=http-response,pattern=https?:\/\/biz\.caiyunapp\.com\/(membership_rights|v2\/user),requires-body=1,script-path=https://raw.githubusercontent.com/deezertidal/private/master/js-backup/Crack/caiyun.js
Picsew=type=http-response,pattern=^https?:\/\/buy\.itunes\.apple\.com\/verifyReceipt$,requires-body=1,script-path=https://raw.githubusercontent.com/Cydia8888/loon_config/master/js/Picsew.js
酷我音乐完美解锁=type=http-response,pattern=^https?:\/\/.*\.(kuwo|lrts)\.(cn|me)\/(a\.p|music\.pay|(vip\/(v2|enc)\/(theme|user\/vip))|(EcomResource|(Mobile)?Ad)Serv(er|ice)).*,requires-body=1,script-path=https://raw.githubusercontent.com/nameking77/Qx/main/rewrite/kw.js
WPS会员=type=http-response,pattern=^https?:\/\/.*?account\.wps\.(com|cn)(:\d+)?\/api\/users\/\w+\/overview$,script-path=https://raw.githubusercontent.com/I-am-R-E/Functional-Store-Hub/Master/WPSOffice/Script/WPS.js,requires-body=1,timeout=10
稻壳1=type=http-request,pattern=^https?:\/\/.+\.(docer.)?wps.cn\/(user\/v1\/vip|android\/mb\/buy|download\/v1\/ios|partner\/invoke\/usable|(api|rank)\/v1(\/mobile\/mb)?\/detail),script-path=https://raw.githubusercontent.com/yqc007/QuantumultX/master/WPSDocerVIPowerCrack.js,requires-body=1,timeout=10
稻壳2=type=http-response,pattern=^https?:\/\/account\.wps\.cn\/api\/v3\/mine\/vips,script-path=https://raw.githubusercontent.com/yqc007/QuantumultX/master/WPSDocerVIPuserCrack.js,requires-body=1,timeout=10

[Mitm]
hostname = %APPEND% pan.baidu.com,biz.caiyunapp.com,ad.caiyunapp.com,*.kuwo.cn, *.lrts.me,account.wps.cn,*account.wps.com,*.docer.wps.cn,vipapi.wps.cn

[URL Rewrite]
^https:\/\/ad\.caiyunapp\.com\/ - reject