#!name=去开屏广告
#!desc=原创，需全新应用，开规则进入
#!author=Cydia8888
#!homepage=https://github.com/Cydia8888/loon_config
#!UPDATED: 2022-12-21


[Rule]
# > 屏蔽Filza升级检测
DOMAIN-SUFFIX,tigisoftware.com,reject-drop

[URL Rewrite]
# > 同花顺至尊版
^https?:\/\/adm\.10jqka\.com\.cn\/interface\/ad\/recommend - reject-200

# > 同花顺爱基金
^https?:\/\/fund\.10jqka\.com\.cn\/hqapi\/static\/homepage\/queryinfo\/ - reject-200

# > 天天基金
^https?:\/\/appactive\.1234567\.com\.cn\/AppoperationApi\/OperationService\/GetAppStartImg - reject-dict

[MITM]
hostname = %APPEND% adm.10jqka.com.cn,fund.10jqka.com.cn,appactive.1234567.com.cn
