#!name=去开屏广告
#!desc=自用，需全新应用，开规则进入
#!author=Cydia8888
#!homepage=https://github.com/Cydia8888/loon_config
#!UPDATED: 2022-12-29

[Rule]
# > 屏蔽Filza正版检测
DOMAIN-SUFFIX,tigisoftware.com,REJECT-DROP
# > 敏感词去广告，杀伤力大，可能误杀
DOMAIN-KEYWORD,pglstatp,REJECT
DOMAIN-KEYWORD,pangolin,REJECT-DROP
DOMAIN-KEYWORD,npoe7n7r,REJECT
DOMAIN-KEYWORD,fundtoutiao,REJECT
DOMAIN-KEYWORD,googleads,REJECT

[URL Rewrite]
# > 同花顺至尊版
^https?:\/\/adm\.10jqka\.com\.cn\/interface\/ad\/recommend - reject-200
# > 同花顺爱基金
^https?:\/\/fund\.10jqka\.com\.cn\/hqapi\/static\/homepage\/queryinfo\/ - reject-200
# > 天天基金
^https?:\/\/appactive\.1234567\.com\.cn\/AppoperationApi\/OperationService\/GetAppStartImg - reject-dict
# > 京东
^https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=start - reject-dict
^https?:\/\/api\.m\.jd.com\/client\.action\?functionId=queryMaterialAdverts - reject
^https?:\/\/(bdsp-x|dsp-x)\.jd\.com\/adx\/ - reject
# > 京东金融
^https?:\/\/ms\.jr\.jd\.com\/gw\/generic\/aladdin\/(new)?na\/m\/getLoadingPicture - reject
# > 京东特价版
^https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=lite_SmartPush - REJECT-200
^https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=lite_advertising - REJECT-200
# > 华尔街见闻
^https?:\/\/api-one-wscn\.awtmt\.com\/apiv1\/advertising\/ads\/ - reject

# > ******百度系去广告******
# > 百度地图
^https:\/\/dss0.bdstatic.com\/-0U0bnSm1A5BphGlnYG\/ - reject-200
^https:\/\/dss0\.bdstatic\.com\/.+/tam-ogel\/.+\.(jpg|mp4) - reject
^https?:\/\/tb1.bdstatic.com\/tb\/cms\/ngmis\/adsense\/*.jpg - reject
^https?+:\/\/ss0\.bdstatic\.com/.+?_\d{3}_\d{4}\.jpg - reject-200
^https?:\/\/gss0\.bdstatic\.com\/.+?\/static\/wiseindex\/img\/bd_red_packet\.png - reject-img
^https?:\/\/tb2\.bdstatic\.com\/tb\/mobile\/spb\/widget\/jump - reject-img
# > 百度网盘
^https?:\/\/pan\.baidu\.com\/rest\/\d\.\d\/pcs\/adx - reject
^https?:\/\/pan\.baidu\.com\/act\/api\/activityentry - reject
^https?:\/\/issuecdn\.baidupcs\.com\/issue\/netdisk\/guanggao - reject
^https?:\/\/update.pan.baidu.com\/statistics - reject
^https:\/\/pan\.baidu\.com\/pmall\/order\/privilege\/info - reject
^https:\/\/pan\.baidu\.com\/rest\/.+\/pcs\/adx - reject
^https:\/\/pan\.baidu\.com\/api\/useractivity\/activity - reject
^http:\/\/pan\.baidu\.com\/act\/.+\/bchannel\/list - reject
^https:\/\/pan\.baidu\.com\/api\/certuser\/get - reject
^https:\/\/ndstatic\.cdn\.bcebos\.com\/activity\/welfare\/js\/.+\.js - reject
^https:\/\/ndstatic\.cdn\.bcebos\.com\/activity\/welfare\/index\.html - reject
^https:\/\/staticsns\.cdn\.bcebos\.com\/amis\/.+/banner.png - reject
^http:\/\/rp\.hpplay\.cn\/logouts - reject
^https:\/\/pan\.baidu\.com\/component\/view\/(1510|1130)\?vip - reject

[Script]
京喜去广告=type=http-response,pattern=^https?:\/\/api\.m\.jd\.com\/api\?functionId=delivery_show,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/startup.js
京东去广告_热词=type=http-response,pattern=^https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=hotWords,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/jd_json.js
京东去广告_热搜=type=http-response,pattern=^https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=hotSearchTerms,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/jd_json.js

[MITM]
hostname = %APPEND% adm.10jqka.com.cn,fund.10jqka.com.cn,appactive.1234567.com.cn,ms.jr.jd.com,bdsp-x.jd.com,dsp-x.jd.com,api.m.jd.com,*.awtmt.com,*.bdstatic.com,pan.baidu.com,*.cdn.bcebos.com,rp.hpplay.cn,issuecdn.baidupcs.com,update.pan.baidu.com