#!name=去开屏广告
#!desc=自用，需全新应用，开规则进入
#!author=Cydia8888
#!homepage=https://github.com/Cydia8888/loon_config
#!UPDATED: 2022-12-28

[Rule]
# > 屏蔽Filza正版检测
DOMAIN-SUFFIX,tigisoftware.com,REJECT-DROP

[URL Rewrite]
# > 同花顺至尊版
^https?:\/\/adm\.10jqka\.com\.cn\/interface\/ad\/recommend - reject-200

# > 同花顺爱基金
^https?:\/\/fund\.10jqka\.com\.cn\/hqapi\/static\/homepage\/queryinfo\/ - reject-200

# > 天天基金
^https?:\/\/appactive\.1234567\.com\.cn\/AppoperationApi\/OperationService\/GetAppStartImg - reject-dict

# > 京东
^https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=start - reject-dict
^https?:\/\/api\.m\.jd.com\/client\.action\?functionId=queryMaterialAdverts - reject
^https?:\/\/(bdsp-x|dsp-x)\.jd\.com\/adx\/ - reject

# > 京东金融
^https?:\/\/ms\.jr\.jd\.com\/gw\/generic\/aladdin\/(new)?na\/m\/getLoadingPicture - reject

# > 京东极速版
^https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=lite_SmartPush _ REJECT-200
^https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=lite_advertising _ REJECT-200

[Script]
京喜去广告=type=http-response,pattern=^https?:\/\/api\.m\.jd\.com\/api\?functionId=delivery_show,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/startup.js
京东去广告_热词=type=http-response,pattern=^https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=hotWords,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/jd_json.js
京东去广告_热搜=type=http-response,pattern=^https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=hotSearchTerms,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/jd_json.js

[MITM]
hostname = %APPEND% adm.10jqka.com.cn,fund.10jqka.com.cn,appactive.1234567.com.cn,ms.jr.jd.com,bdsp-x.jd.com,dsp-x.jd.com,api.m.jd.com